version: 2.1

orbs:
 python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          name: run tests
          command: python -m unittest lib/tests/unittests/TestAdoptableSchema.py
      
  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: docker build
          command: docker build -t docker.io/$DOCKER_NAME/graphql:${CIRCLE_BRANCH#*/} .

workflows:
  main:
    jobs:
      - build-and-test
      - docker-build